### ISSUE TITLE
online demo and api doc?

### ISSUE THREAD

**Issue by blurymind** [heithemmoumni/svelte-mindmap#1]
I've done some work on
https://github.com/YarnSpinnerTool/YarnEditor
and have been thinking of rewriting the thing, since it is using a bunch of really outdated libraries and the code is just full of doing stuff from scratch for no reason parts.

I like svelte and also need a library that would allow me to recreate the style of nodes that yarneditor uses. Be able to display node contents, but also summon a full node editor dialog when double clicking on a node.

Now do you think I can get that? How do I get straight line connections with arrows? Can I make custom nodes somehow with this? Can I customize what happens when you double click on a node? How flexible is the api?

**Comment by lettaz** [comment]
Hi @blurymind, I am also looking for a tool that does this same thing you have said, did you have anyluck finding?

**Comment by heithemmoumni** [comment]
resolved
