### ISSUE TITLE
Error when running with Snowpack (via SvelteKit, etc.)

### ISSUE THREAD

**Issue by aral** [heithemmoumni/svelte-mindmap#9]
I haven’t tested without Snowpack (so I’m not sure if this is a Snowpack-specific issue) but on latest SvelteKit (as well as on my own non-SveltKit setup that uses Snowpack), I am getting the following error when I click into the Mindmap area after the component loads (empty  canvas):

```
node.getScreenCTM() is null
```

## To reproduce

```
mkdir sveltekit-mindmap
cd sveltekit-mindmap
npm init svelte@next
npm install
npm install svelte-mindmap
```

Then, add the example in the readme to `routes/index.svelte`

Finally, run it with:

```
npm run dev
```

**Comment by alephpt** [comment]
use vite@latest

**Comment by heithemmoumni** [comment]
resolved
